title: "<Your Name>'s Resume"
description: "A simple online resume"
url: "https://<your-username>.github.io/PersonalWebsite"
baseurl: "/resume"
remote_theme: "LeNPaul/academic"
plugins:
  - jekyll-remote-theme
